name: test23
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17

flutter_native_splash:
  color: "#f7f6f1"
  dark_color: "#272727"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#272727"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/


